# Generated by Django 2.2.5 on 2019-09-30 07:18

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('quora_api', '0002_auto_20190929_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuora',
        ),
        migrations.CreateModel(
            name='UserQuora',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
