# Generated by Django 2.2.5 on 2019-09-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora_api', '0003_auto_20190930_0718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuora',
        ),
    ]
