# Generated by Django 2.2.5 on 2019-10-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quora_api', '0005_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='url_title',
            field=models.CharField(default='tutu', max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quora_api.Question'),
        ),
    ]
