# Generated by Django 2.2.5 on 2019-10-07 18:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quora_api', '0009_auto_20191007_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='liker',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker', 'answer')},
        ),
    ]
